version: "3.8"
services:
  mongo:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null
    restart: always
    environment:
      # Provide your credentials here
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo

  wc-api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    restart: always
    ports:
      - 4005:4005
    depends_on:
      - mongo
    volumes:
      - cdn:/var/www/cdn/wexcommerce
      - api_logs:/wexcommerce/api/logs

  wc-admin:
    build:
      context: .
      dockerfile: ./admin/Dockerfile
    depends_on:
      - wc-api
    ports:
      - 8005:8005
    restart: always

  wc-nginx-admin:
    build:
      context: .
      dockerfile: ./admin/nginx/Dockerfile
    depends_on:
      - wc-admin
    ports:
      - 8001:8001
    restart: always

  wc-frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    depends_on:
      - wc-api
    ports:
      - 8006:8006
    volumes:
      - cdn:/var/www/cdn/wexcommerce
    restart: always

  wc-nginx-frontend:
    build:
      context: .
      dockerfile: ./frontend/nginx/Dockerfile
    depends_on:
      - wc-frontend
    ports:
      - 8080:80
      - 4443:443
    volumes:
      - cdn:/var/www/cdn/wexcommerce
    restart: always

volumes:
  cdn:
  mongodb_data:
  mongodb_config:
  api_logs:
