FROM node:lts-alpine AS packages
WORKDIR /wexcommerce/packages

COPY ./packages /wexcommerce/packages

# Install dependencies for all internal packages
RUN set -e && \
  find ./ -mindepth 1 -maxdepth 1 -type d \
  -exec sh -c 'for dir; do \
    if [ -f "$dir/package.json" ]; then \
      echo "Installing dependencies in $dir"; \
      npm --prefix "$dir" install; \
    fi; \
  done' _ {} +

FROM node:lts-alpine AS backend
WORKDIR /wexcommerce/backend

COPY ./backend/package*.json ./
RUN npm install --force && npm cache clean --force

COPY ./backend ./ 
COPY ./backend/.env.docker.development .env

# Copy preinstalled internal packages
COPY --from=packages /wexcommerce/packages /wexcommerce/packages

EXPOSE 8005
CMD ["npm", "run", "dev:docker"]
